import React from 'react';

export default props => (
    <div>
        <h1 className='text-center'>Soocroot doocs</h1>
        <p>MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS </p>
        <p>MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS </p>
        <p>MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS </p>
        <p>MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS </p>
        <p>MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS MANY IPSUMS </p>
    </div>
)